In [1]:
# 十大事件
event_list = ['trafficSource', 'userRegisteration', 'mainPageView', 'productPageView', 'categoryPageView',
              'activityPageView', 'search', 'addToCart', 'checkout', 'purchase']

bh_list = ['traffic', 'viewproduct', 'add', 'viewcategory', 'viewmainpage', 'register', 'checkout', 'search',
           'purchase', 'viewactivity']

In [2]:
import pandas as pd
import numpy as np

In [3]:
did_uid_data = pd.read_csv('20200501 - 20210430 uid _ did.csv', encoding = "utf-8", engine='python')

In [7]:
print('file length:', len(did_uid_data))
print('did length:', len(did_uid_data.did.unique()))
print('did length:', len(did_uid_data.uid.unique()))

file length: 12548
did length: 8681
did length: 6284

In [8]:
dids = list(did_uid_data.did.unique())
uids = list(did_uid_data.uid.unique())

In [36]:
def merge_data(events, dates, did_list):
    i = 1
    for date_str in dates:
        print(date_str)
        for event in events:
            path = './dataset/91APP_BehaviorData/' + event + '_' + date_str + '.csv'

            df_origin = pd.read_csv(path, encoding = "utf-8")
            
            if i == 1:
                df = df_origin.loc[df_origin['did'].isin(did_list)]
            else:
                df1 = df_origin.loc[df_origin['did'].isin(did_list)]
                df = pd.concat([df, df1])
            i += 1

    df['DateTime'] = pd.to_datetime(df.ht, unit='ms')

    df = df.sort_values(by = ['did', 'dc', 'DateTime'])
    df = df[['dc', 'did', 'uid', 'DateTime', 'bh', 'cs', 'cm', 'cn', 'pr', 'pr1id', 'pr1pr', 'pr1qt', 'cu', 'tr', 'ti']]
    
    return df

In [40]:
from datetime import date, timedelta
date_range=pd.date_range(date(2020,5,1),date(2021,4,30))
date_list=[x.strftime('%F')for x in date_range]

In [41]:
len(date_list)

365

In [43]:
data = merge_data(event_list, date_list, dids)

2020-05-01
2020-05-02
2020-05-03
2020-05-04
2020-05-05
2020-05-06
2020-05-07
2020-05-08
2020-05-09
2020-05-10
2020-05-11
2020-05-12
2020-05-13
2020-05-14
2020-05-15
2020-05-16
2020-05-17
2020-05-18
2020-05-19
2020-05-20
2020-05-21
2020-05-22
2020-05-23
2020-05-24
2020-05-25
2020-05-26
2020-05-27
2020-05-28
2020-05-29
2020-05-30
2020-05-31
2020-06-01
2020-06-02
2020-06-03
2020-06-04
2020-06-05
2020-06-06
2020-06-07
2020-06-08
2020-06-09
2020-06-10
2020-06-11
2020-06-12
2020-06-13
2020-06-14
2020-06-15
2020-06-16
2020-06-17
2020-06-18
2020-06-19
2020-06-20
2020-06-21
2020-06-22
2020-06-23
2020-06-24
2020-06-25
2020-06-26
2020-06-27
2020-06-28
2020-06-29
2020-06-30
2020-07-01
2020-07-02
2020-07-03
2020-07-04
2020-07-05
2020-07-06
2020-07-07
2020-07-08
2020-07-09
2020-07-10
2020-07-11
2020-07-12
2020-07-13
2020-07-14
2020-07-15
2020-07-16
2020-07-17
2020-07-18
2020-07-19
2020-07-20
2020-07-21
2020-07-22
2020-07-23
2020-07-24
2020-07-25
2020-07-26
2020-07-27
2020-07-28
2020-07-29
2020-07-30
2020-07-31
2020-08-01
2020-08-02
2020-08-03
2020-08-04
2020-08-05
2020-08-06
2020-08-07
2020-08-08
2020-08-09
2020-08-10
2020-08-11
2020-08-12
2020-08-13
2020-08-14
2020-08-15
2020-08-16
2020-08-17
2020-08-18
2020-08-19
2020-08-20
2020-08-21
2020-08-22
2020-08-23
2020-08-24
2020-08-25
2020-08-26
2020-08-27
2020-08-28
2020-08-29
2020-08-30
2020-08-31
2020-09-01
2020-09-02
2020-09-03
2020-09-04
2020-09-05
2020-09-06
2020-09-07
2020-09-08
2020-09-09
2020-09-10
2020-09-11
2020-09-12
2020-09-13
2020-09-14
2020-09-15
2020-09-16
2020-09-17
2020-09-18
2020-09-19
2020-09-20
2020-09-21
2020-09-22
2020-09-23
2020-09-24
2020-09-25
2020-09-26
2020-09-27
2020-09-28
2020-09-29
2020-09-30
2020-10-01
2020-10-02
2020-10-03
2020-10-04
2020-10-05
2020-10-06
2020-10-07
2020-10-08
2020-10-09
2020-10-10
2020-10-11
2020-10-12
2020-10-13
2020-10-14
2020-10-15
2020-10-16
2020-10-17
2020-10-18
2020-10-19
2020-10-20
2020-10-21
2020-10-22
2020-10-23
2020-10-24
2020-10-25
2020-10-26
2020-10-27
2020-10-28
2020-10-29
2020-10-30
2020-10-31
2020-11-01
2020-11-02
2020-11-03
2020-11-04
2020-11-05
2020-11-06
2020-11-07
2020-11-08
2020-11-09
2020-11-10
2020-11-11
2020-11-12
2020-11-13
2020-11-14
2020-11-15
2020-11-16
2020-11-17
2020-11-18
2020-11-19
2020-11-20
2020-11-21
2020-11-22
2020-11-23
2020-11-24
2020-11-25
2020-11-26
2020-11-27
2020-11-28
2020-11-29
2020-11-30
2020-12-01
2020-12-02
2020-12-03
2020-12-04
2020-12-05
2020-12-06
2020-12-07
2020-12-08
2020-12-09
2020-12-10
2020-12-11
2020-12-12
2020-12-13
2020-12-14
2020-12-15
2020-12-16
2020-12-17
2020-12-18
2020-12-19
2020-12-20
2020-12-21
2020-12-22
2020-12-23
2020-12-24
2020-12-25
2020-12-26
2020-12-27
2020-12-28
2020-12-29
2020-12-30
2020-12-31
2021-01-01
2021-01-02
2021-01-03
2021-01-04
2021-01-05
2021-01-06
2021-01-07
2021-01-08
2021-01-09
2021-01-10
2021-01-11
2021-01-12
2021-01-13
2021-01-14
2021-01-15
2021-01-16
2021-01-17
2021-01-18
2021-01-19
2021-01-20
2021-01-21
2021-01-22
2021-01-23
2021-01-24
2021-01-25
2021-01-26
2021-01-27
2021-01-28
2021-01-29
2021-01-30
2021-01-31
2021-02-01
2021-02-02
2021-02-03
2021-02-04
2021-02-05
2021-02-06
2021-02-07
2021-02-08
2021-02-09
2021-02-10
2021-02-11
2021-02-12
2021-02-13
2021-02-14
2021-02-15
2021-02-16
2021-02-17
2021-02-18
2021-02-19
2021-02-20
2021-02-21
2021-02-22
2021-02-23
2021-02-24
2021-02-25
2021-02-26
2021-02-27
2021-02-28
2021-03-01
2021-03-02
2021-03-03
2021-03-04
2021-03-05
2021-03-06
2021-03-07
2021-03-08
2021-03-09
2021-03-10
2021-03-11
2021-03-12
2021-03-13
2021-03-14
2021-03-15
2021-03-16
2021-03-17
2021-03-18
2021-03-19
2021-03-20
2021-03-21
2021-03-22
2021-03-23
2021-03-24
2021-03-25
2021-03-26
2021-03-27
2021-03-28
2021-03-29
2021-03-30
2021-03-31
2021-04-01
2021-04-02
2021-04-03
2021-04-04
2021-04-05
2021-04-06
2021-04-07
2021-04-08
2021-04-09
2021-04-10
2021-04-11
2021-04-12
2021-04-13
2021-04-14
2021-04-15
2021-04-16
2021-04-17
2021-04-18
2021-04-19
2021-04-20
2021-04-21
2021-04-22
2021-04-23
2021-04-24
2021-04-25
2021-04-26
2021-04-27
2021-04-28
2021-04-29
2021-04-30

In [44]:
len(data.uid.unique())

6507

In [45]:
data.to_csv('合併行為資料-20200501~20210430.csv', index = False, encoding = "utf-8")

In [75]:
data.reset_index(inplace=True)

In [76]:
data

,index,dc,did,uid,DateTime,bh,cs,cm,cn,pr,pr1id,pr1pr,pr1qt,cu,tr,ti
0,17548,web,0006b8f7-94a5-4387-0d56-0b5631e85cba,NaN,2020-10-21 05:10:40.691,traffic,m.facebook.com,referral,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,17692,web,0006b8f7-94a5-4387-0d56-0b5631e85cba,NaN,2020-10-21 05:10:40.691,viewproduct,NaN,NaN,NaN,NaN,5783099.0,2080.0,1.0,TWD,NaN,NaN
2,6176,web,0006b8f7-94a5-4387-0d56-0b5631e85cba,NaN,2020-11-11 10:17:43.351,traffic,FBAD,202010052200B289222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25452,web,0006b8f7-94a5-4387-0d56-0b5631e85cba,NaN,2020-11-11 10:17:43.351,viewcategory,NaN,NaN,NaN,289222,NaN,NaN,NaN,NaN,NaN,NaN
4,45592,web,0006b8f7-94a5-4387-0d56-0b5631e85cba,NaN,2020-11-11 10:18:03.344,viewproduct,NaN,NaN,NaN,NaN,4955890.0,1980.0,1.0,TWD,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1503893,14198,web,fffafbb4-33a8-428d-e644-3d170f184932,pnqTjjRPvh8bk8tI2faFFmOheVPm91Go%2FeOi%2BMKCLx...,2020-12-13 14:06:16.165,viewcategory,NaN,NaN,NaN,170755,NaN,NaN,NaN,NaN,NaN,NaN
1503894,20958,web,fffafbb4-33a8-428d-e644-3d170f184932,pnqTjjRPvh8bk8tI2faFFmOheVPm91Go%2FeOi%2BMKCLx...,2020-12-13 14:06:36.522,viewproduct,NaN,NaN,NaN,NaN,6012006.0,2180.0,1.0,TWD,NaN,NaN
1503895,22407,web,fffafbb4-33a8-428d-e644-3d170f184932,pnqTjjRPvh8bk8tI2faFFmOheVPm91Go%2FeOi%2BMKCLx...,2020-12-13 14:07:09.678,viewproduct,NaN,NaN,NaN,NaN,4841961.0,1480.0,1.0,TWD,NaN,NaN
1503896,657,web,fffafbb4-33a8-428d-e644-3d170f184932,pnqTjjRPvh8bk8tI2faFFmOheVPm91Go%2FeOi%2BMKCLx...,2020-12-13 14:32:42.031,checkout,NaN,NaN,NaN,NaN,4841961.0,1480.0,1.0,TWD,NaN,NaN
1503897,431,web,fffafbb4-33a8-428d-e644-3d170f184932,pnqTjjRPvh8bk8tI2faFFmOheVPm91Go%2FeOi%2BMKCLx...,2020-12-13 14:33:16.558,purchase,NaN,NaN,NaN,NaN,4841961.0,1480.0,1.0,TWD,1480.0,TG201213Y01869

In [47]:
len(data)

1503898

In [78]:
num_group = data.groupby(by="did").DateTime.count()

In [81]:
num_group

did
0006b8f7-94a5-4387-0d56-0b5631e85cba     64
0007e063-52b6-4f0c-a5b7-9be218c66894    513
000e144b-761a-4a6c-a5fb-3973a8f2fbf4    120
001a00ba-e5da-480b-4876-d5e9e6ca6ddf     73
0022f3fc-ea97-48a7-9926-8e56545e2e9f     10
                                       ...
ffd2c84e-34ec-4b96-b7f0-92c7df860081    195
ffd45603-9eef-407f-b895-66b24f7ae073     38
ffd49cbd-549a-451a-98fe-ae18ecfb4435     89
ffebf9ea-2b82-46d6-ac72-80844b3ec2e6    545
fffafbb4-33a8-428d-e644-3d170f184932     26
Name: DateTime, Length: 8681, dtype: int64

In [83]:
num_list = []
num_keys = num_group.keys()

for i in range(len(num_keys)):
    num_list.append({
        'did': num_keys[i],
        '資料筆數': num_group[i]
    })

In [84]:
num_df = pd.DataFrame(num_list)

In [87]:
num_df.to_csv('did資料筆數統計.csv', index = False, encoding = "big5")

## 因資料量太大 分組輸出資料

In [91]:
df = df_origin.loc[data['did'].isin(did_list)]

In [111]:
count = 0
for i in range(1,19):
    start = (i-1) * 500
    end = i * 500
    print(start, end)
    did_spilt = dids[start:end]
    
    data_split = data.loc[data['did'].isin(did_spilt)]
    count += len(data_split)
    print(len(data_split), 'count', count)
    data_split.to_csv('合併行為資料-20200501~20210430-'+ str(i) +'.csv', index = False, encoding = "utf-8")

0 500
233906 count 233906
500 1000
119139 count 353045
1000 1500
102579 count 455624
1500 2000
110044 count 565668
2000 2500
103711 count 669379
2500 3000
97226 count 766605
3000 3500
96012 count 862617
3500 4000
75657 count 938274
4000 4500
62150 count 1000424
4500 5000
64157 count 1064581
5000 5500
61442 count 1126023
5500 6000
60415 count 1186438
6000 6500
58903 count 1245341
6500 7000
60556 count 1305897
7000 7500
58124 count 1364021
7500 8000
65761 count 1429782
8000 8500
55493 count 1485275
8500 9000
18623 count 1503898

In [99]:
len(dids[8000:9000])

681

## 會對應到不同 uid 的did 個數

In [53]:
group_did = data.groupby(by="did").uid.unique()

In [55]:
group_df = pd.DataFrame(group_did)

In [69]:
type(group_did)
group_did.keys()[31]

'0149d152-3883-415f-bd8f-b792afefe5c4'

In [62]:
non_unique_uid = []
for i in range(len(group_did)):
    did = group_did[i]
    no_na = did[~pd.isna(did)]
    
    if len(no_na)>1:
        non_unique_uid.append(i)

In [92]:
# non_unique_uid

In [80]:
len(non_unique_uid)

212

In [70]:
non_unique = []
group_keys = group_did.keys()

for i in non_unique_uid:
    non_unique.append({
        'did': group_keys[i],
        'uids': group_did[i]
    })

In [71]:
non_unique_df = pd.DataFrame(non_unique)

In [73]:
non_unique_df.to_csv('did對應多個uid.csv', index = False, encoding = "utf-8")