In [2]:
import numpy as np
import pandas as pd
import calendar

In [24]:
# preprocess=pd.read_csv('preprocess.csv', engine='python',index_col="arrival_date")
train=pd.read_csv('preprocess_all/preprocess_train_num_all.csv', engine='python',index_col="arrival_date")
# train=train.drop(["label"],axis=1)
train

,hotel_Resort,hotel_City,lead_time,arrival_date_week_number,stays_nights,adults,children,babies,meal_BB,meal_FB,...,wait_less_than_3,wait_between_3_30,wait_greater_than_30,contract,group,transient,transient_party,mean_required_car_parking_space,special_requests_ratio,quatity
arrival_date,,,,,,,,,,,,,,,,,,,,,
2015/7/1,38,65,190.291262,27,3.048544,1.805825,0.019417,0.000000,35,1,...,103,0,0,6,0,97,0,0.038835,0.184466,103
2015/7/2,35,1,69.944444,27,5.694444,1.972222,0.055556,0.000000,27,1,...,36,0,0,13,0,20,3,0.138889,0.500000,36
2015/7/3,27,10,65.378378,27,4.324324,2.000000,0.081081,0.000000,22,0,...,37,0,0,6,0,22,9,0.189189,0.243243,37
2015/7/4,36,9,120.777778,27,5.311111,1.977778,0.111111,0.044444,37,1,...,45,0,0,7,0,26,12,0.155556,0.488889,45
2015/7/5,37,0,75.378378,28,6.108108,1.945946,0.216216,0.000000,26,0,...,37,0,0,9,1,27,0,0.351351,0.378378,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/3/27,25,89,96.368421,13,2.982456,1.842105,0.000000,0.000000,99,0,...,114,0,0,0,2,67,45,0.070175,0.675439,114
2017/3/28,33,34,52.537313,13,3.820896,1.791045,0.044776,0.014925,54,0,...,67,0,0,0,1,64,2,0.059701,0.492537,67
2017/3/29,51,79,41.130769,13,2.800000,1.653846,0.053846,0.015385,104,0,...,130,0,0,0,3,125,2,0.100000,0.484615,130
2017/3/30,51,73,59.137097,13,3.596774,1.725806,0.040323,0.024194,85,0,...,124,0,0,3,0,102,19,0.072581,0.508065,124
2017/3/31,64,76,58.053846,13,3.084615,1.846154,0.069231,0.000000,98,0,...,130,0,0,4,1,123,2,0.061538,0.592308,130

In [25]:
test=pd.read_csv('preprocess_all/preprocess_test_num_all.csv', engine='python',index_col="arrival_date")
test

,hotel_Resort,hotel_City,lead_time,arrival_date_week_number,stays_nights,adults,children,babies,meal_BB,meal_FB,...,wait_less_than_3,wait_between_3_30,wait_greater_than_30,contract,group,transient,transient_party,mean_required_car_parking_space,special_requests_ratio,quatity
arrival_date,,,,,,,,,,,,,,,,,,,,,
2017/4/1,35,97,95.265152,13,3.969697,2.068182,0.151515,0.007576,106,0,...,129,0,3,1,0,106,25,0.053030,0.409091,132
2017/4/2,29,67,73.364583,14,3.822917,1.947917,0.083333,0.010417,73,0,...,95,0,1,4,0,88,4,0.052083,0.520833,96
2017/4/3,64,167,76.995671,14,3.307359,1.761905,0.082251,0.004329,203,0,...,229,0,2,4,3,175,49,0.038961,0.415584,231
2017/4/4,28,97,104.544000,14,3.048000,1.912000,0.152000,0.000000,111,0,...,123,2,0,0,0,111,14,0.056000,0.360000,125
2017/4/5,91,161,119.769841,14,3.484127,1.702381,0.051587,0.000000,232,0,...,247,1,4,1,0,133,118,0.067460,0.190476,252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017/8/27,67,107,93.954023,35,3.178161,1.948276,0.258621,0.000000,115,2,...,174,0,0,3,2,151,18,0.068966,0.643678,174
2017/8/28,78,133,139.222749,35,4.374408,1.696682,0.151659,0.004739,101,3,...,211,0,0,4,2,133,72,0.056872,0.450237,211
2017/8/29,35,90,141.672000,35,3.888000,1.816000,0.168000,0.000000,93,0,...,125,0,0,2,2,119,2,0.048000,0.600000,125
2017/8/30,42,47,98.303371,35,3.921348,1.955056,0.213483,0.011236,69,0,...,89,0,0,0,4,83,2,0.056180,0.561798,89
2017/8/31,55,79,110.888060,35,3.955224,2.044776,0.141791,0.000000,95,0,...,134,0,0,8,1,112,13,0.089552,0.686567,134

In [5]:
y_label=pd.read_csv('train_label.csv', engine='python',index_col="arrival_date")
test_nolabel = pd.read_csv('test_nolabel.csv', engine='python')

In [6]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()
tree.fit(train,y_label)
test_pre=tree.predict(test)

In [7]:
test_pre=pd.DataFrame(test_pre,columns=["label"])
test_pre

     label
0      5.0
1      2.0
2      4.0
3      5.0
4      4.0
..     ...
148    8.0
149    8.0
150    6.0
151    4.0
152    8.0

[153 rows x 1 columns]

In [8]:
y_test= pd.concat([test_nolabel,test_pre],axis=1)

In [14]:
import csv

# 開啟輸出的 CSV 檔案
with open('model_predict/decision_tree.csv', 'w', newline='') as csvfile:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvfile)

    # 寫入標題資料
    writer.writerow(["arrival_date","label"])
    # 寫入距離資料
    for i in range(len(y_test)):
        writer.writerow([y_test["arrival_date"].iloc[i],y_test["label"].iloc[i]])

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=2, random_state=0)
rf.fit(train,y_label)
test_pre_rf=rf.predict(test)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

In [16]:
test_pre_rf=pd.DataFrame(test_pre_rf,columns=["label"])
test_pre_rf

     label
0      3.0
1      2.0
2      2.0
3      2.0
4      2.0
..     ...
148    3.0
149    2.0
150    2.0
151    2.0
152    3.0

[153 rows x 1 columns]

In [17]:
y_test_rf= pd.concat([test_nolabel,test_pre_rf],axis=1)

In [18]:
import csv

# 開啟輸出的 CSV 檔案
with open('model_predict/random_forest.csv', 'w', newline='') as csvfile:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvfile)

    # 寫入標題資料
    writer.writerow(["arrival_date","label"])
    # 寫入距離資料
    for i in range(len(y_test_rf)):
        writer.writerow([y_test_rf["arrival_date"].iloc[i],y_test_rf["label"].iloc[i]])

In [19]:
from sklearn.ensemble import AdaBoostClassifier
ab=AdaBoostClassifier()
ab.fit(train,y_label)
test_pre_ab=ab.predict(test)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [20]:
test_pre_ab=pd.DataFrame(test_pre_ab,columns=["label"])
test_pre_ab

     label
0      2.0
1      2.0
2      2.0
3      2.0
4      2.0
..     ...
148    2.0
149    2.0
150    2.0
151    2.0
152    2.0

[153 rows x 1 columns]

In [21]:
y_test_ab= pd.concat([test_nolabel,test_pre_ab],axis=1)

In [22]:
import csv

# 開啟輸出的 CSV 檔案
with open('model_predict/AdaBoost.csv', 'w', newline='') as csvfile:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvfile)

    # 寫入標題資料
    writer.writerow(["arrival_date","label"])
    # 寫入距離資料
    for i in range(len(y_test_ab)):
        writer.writerow([y_test_ab["arrival_date"].iloc[i],y_test_ab["label"].iloc[i]])

In [23]:
y_test_ab

    arrival_date  label
0     2017-04-01    2.0
1     2017-04-02    2.0
2     2017-04-03    2.0
3     2017-04-04    2.0
4     2017-04-05    2.0
..           ...    ...
148   2017-08-27    2.0
149   2017-08-28    2.0
150   2017-08-29    2.0
151   2017-08-30    2.0
152   2017-08-31    2.0

[153 rows x 2 columns]

In [30]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=100)
gb.fit(train, y_label)
test_pre_gb = gb.predict(test)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

In [34]:
test_pre_gb=pd.DataFrame(test_pre_gb,columns=["label"])
test_pre_gb

     label
0      3.0
1      3.0
2      4.0
3      3.0
4      4.0
..     ...
148    4.0
149    8.0
150    3.0
151    2.0
152    3.0

[153 rows x 1 columns]

In [35]:
y_test_gb= pd.concat([test_nolabel,test_pre_gb],axis=1)

In [36]:
import csv

# 開啟輸出的 CSV 檔案
with open('model_predict/GradientBoosting.csv', 'w', newline='') as csvfile:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvfile)

    # 寫入標題資料
    writer.writerow(["arrival_date","label"])
    # 寫入距離資料
    for i in range(len(y_test_gb)):
        writer.writerow([y_test_gb["arrival_date"].iloc[i],y_test_gb["label"].iloc[i]])

In [18]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten,LSTM,Embedding
from keras import optimizers
from keras.callbacks import EarlyStopping

Using TensorFlow backend.

In [99]:
n_steps = 3
n_features = 10
model = Sequential()

# model.add(Embedding(input_dim=43, output_dim=128))
model.add(LSTM(units = 64, input_dim=42))
# model.add(LSTM(units = 64,return_sequences=True))#new
model.add(Dense(32))
model.add(Dense(16))
model.add(Dense(10, activation='sigmoid'))
model.summary()

Model: "sequential_20"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
lstm_20 (LSTM)               (None, 64)                27392
_________________________________________________________________
dense_35 (Dense)             (None, 32)                2080
_________________________________________________________________
dense_36 (Dense)             (None, 16)                528
_________________________________________________________________
dense_37 (Dense)             (None, 10)                170
=================================================================
Total params: 30,170
Trainable params: 30,170
Non-trainable params: 0
_________________________________________________________________

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: The `input_dim` and `input_length` arguments in recurrent layers are deprecated. Use `input_shape` instead.

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(units=64, input_shape=(None, 42))`

In [100]:
import numpy as np
train_lstm=np.array(train)
X_train = np.reshape(train_lstm, (train_lstm.shape[0], 1, train_lstm.shape[1]))
test_lstm=np.array(test)
X_test = np.reshape(test_lstm, (test_lstm.shape[0], 1, test_lstm.shape[1]))
y_label_tr=pd.get_dummies(y_label, columns=["label"])

In [104]:
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
# model.compile(loss='mean_squared_error', optimizer='adam')
hist = model.fit(X_train, y_label_tr, batch_size=20, epochs=40, verbose=1)

Epoch 1/40
640/640 [==============================] - 1s 1ms/step - loss: 0.1649 - accuracy: 0.9223
Epoch 2/40
640/640 [==============================] - 0s 128us/step - loss: 0.1650 - accuracy: 0.9244
Epoch 3/40
640/640 [==============================] - 0s 137us/step - loss: 0.1628 - accuracy: 0.9264
Epoch 4/40
640/640 [==============================] - 0s 122us/step - loss: 0.1610 - accuracy: 0.9259
Epoch 5/40
640/640 [==============================] - 0s 117us/step - loss: 0.1580 - accuracy: 0.9272
Epoch 6/40
640/640 [==============================] - 0s 123us/step - loss: 0.1558 - accuracy: 0.9269
Epoch 7/40
640/640 [==============================] - 0s 127us/step - loss: 0.1528 - accuracy: 0.9275
Epoch 8/40
640/640 [==============================] - 0s 151us/step - loss: 0.1533 - accuracy: 0.9269
Epoch 9/40
640/640 [==============================] - 0s 127us/step - loss: 0.1526 - accuracy: 0.9294
Epoch 10/40
640/640 [==============================] - 0s 124us/step - loss: 0.1523 - accuracy: 0.9275
Epoch 11/40
640/640 [==============================] - 0s 126us/step - loss: 0.1519 - accuracy: 0.9283
Epoch 12/40
640/640 [==============================] - 0s 121us/step - loss: 0.1517 - accuracy: 0.9297
Epoch 13/40
640/640 [==============================] - 0s 115us/step - loss: 0.1529 - accuracy: 0.9311
Epoch 14/40
640/640 [==============================] - 0s 118us/step - loss: 0.1538 - accuracy: 0.9291
Epoch 15/40
640/640 [==============================] - 0s 117us/step - loss: 0.1492 - accuracy: 0.9320
Epoch 16/40
640/640 [==============================] - 0s 123us/step - loss: 0.1480 - accuracy: 0.9309
Epoch 17/40
640/640 [==============================] - 0s 136us/step - loss: 0.1462 - accuracy: 0.9330
Epoch 18/40
640/640 [==============================] - 0s 135us/step - loss: 0.1468 - accuracy: 0.9322
Epoch 19/40
640/640 [==============================] - 0s 119us/step - loss: 0.1487 - accuracy: 0.9288
Epoch 20/40
640/640 [==============================] - 0s 118us/step - loss: 0.1473 - accuracy: 0.9323
Epoch 21/40
640/640 [==============================] - 0s 118us/step - loss: 0.1434 - accuracy: 0.9322
Epoch 22/40
640/640 [==============================] - 0s 128us/step - loss: 0.1429 - accuracy: 0.9333
Epoch 23/40
640/640 [==============================] - 0s 127us/step - loss: 0.1438 - accuracy: 0.9337
Epoch 24/40
640/640 [==============================] - 0s 128us/step - loss: 0.1428 - accuracy: 0.9344
Epoch 25/40
640/640 [==============================] - 0s 128us/step - loss: 0.1502 - accuracy: 0.9288
Epoch 26/40
640/640 [==============================] - 0s 128us/step - loss: 0.1462 - accuracy: 0.9309
Epoch 27/40
640/640 [==============================] - 0s 127us/step - loss: 0.1535 - accuracy: 0.9311
Epoch 28/40
640/640 [==============================] - 0s 121us/step - loss: 0.1409 - accuracy: 0.9341
Epoch 29/40
640/640 [==============================] - 0s 118us/step - loss: 0.1403 - accuracy: 0.9361
Epoch 30/40
640/640 [==============================] - 0s 116us/step - loss: 0.1423 - accuracy: 0.9342
Epoch 31/40
640/640 [==============================] - 0s 119us/step - loss: 0.1433 - accuracy: 0.9356
Epoch 32/40
640/640 [==============================] - 0s 116us/step - loss: 0.1386 - accuracy: 0.9375
Epoch 33/40
640/640 [==============================] - 0s 121us/step - loss: 0.1419 - accuracy: 0.9345
Epoch 34/40
640/640 [==============================] - 0s 120us/step - loss: 0.1384 - accuracy: 0.9355
Epoch 35/40
640/640 [==============================] - 0s 117us/step - loss: 0.1414 - accuracy: 0.9337
Epoch 36/40
640/640 [==============================] - 0s 119us/step - loss: 0.1409 - accuracy: 0.9352
Epoch 37/40
640/640 [==============================] - 0s 116us/step - loss: 0.1405 - accuracy: 0.9352
Epoch 38/40
640/640 [==============================] - 0s 119us/step - loss: 0.1364 - accuracy: 0.9377
Epoch 39/40
640/640 [==============================] - 0s 119us/step - loss: 0.1337 - accuracy: 0.9406
Epoch 40/40
640/640 [==============================] - 0s 125us/step - loss: 0.1374 - accuracy: 0.9389

In [73]:
test_pre_lstm=np.argmax(model.predict(X_test), axis=1)
test_pre_lstm

[3 2 3 1 1 1 1 3 1 2 2 3 3 3 3 3 3 3 2 3 1 1 3 2 1 1 3 3 3 2 1 3 1 1 3 3 3
 3 5 3 3 3 3 3 1 3 3 3 1 3 3 3 3 2 3 6 3 1 6 1 1 3 3 1 6 6 5 5 1 3 2 6 6 6
 1 6 6 5 6 5 6 5 6 1 5 6 5 5 1 6 3 2 5 1 6 5 5 1 5 3 6 5 5 6 2 6 2 6 6 2 6
 6 6 5 6 5 8 5 6 6 6 5 5 6 6 5 6 2 1 6 4 5 6 6 6 1 6 5 6 3 6 6 6 3 5 3 6 6
 3 6 5 2 3]

In [74]:
test_pre_lstm=pd.DataFrame(test_pre_lstm,columns=["label"])
y_test_lstm= pd.concat([test_nolabel,test_pre_lstm],axis=1)

In [75]:
import csv

# 開啟輸出的 CSV 檔案
with open('model_predict/LSTM.csv', 'w', newline='') as csvfile:
    # 建立 CSV 檔寫入器
    writer = csv.writer(csvfile)

    # 寫入標題資料
    writer.writerow(["arrival_date","label"])
    # 寫入距離資料
    for i in range(len(y_test_lstm)):
        writer.writerow([y_test_lstm["arrival_date"].iloc[i],y_test_lstm["label"].iloc[i]])

In [71]:
import xgboost as xgb

ModuleNotFoundError: No module named 'xgboost'

In [52]:
import xgboost as xgb
dtrain = xgb.DMatrix(train, label=y_label)
param = {'max_depth': 2, 'eta': 1, 'objective': 'binary:logistic'}
param['nthread'] = 4
param['eval_metric'] = 'auc'
bst = xgb.train(param, dtrain, num_round, evallist)
ypred = bst.predict(test, ntree_limit=bst.best_ntree_limit)

XGBoostError: XGBoost Library (libxgboost.dylib) could not be loaded.
Likely causes:
  * OpenMP runtime is not installed (vcomp140.dll or libgomp-1.dll for Windows, libomp.dylib for Mac OSX, libgomp.so for Linux and other UNIX-like OSes). Mac OSX users: Run `brew install libomp` to install OpenMP runtime.
  * You are running 32-bit Python on a 64-bit OS
Error message(s): ['dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib, 6): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib\n  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xgboost/lib/libxgboost.dylib\n  Reason: image not found']